import streamlit as st


def render_data_visualization_tab(X, y, drift_point, feature_names, all_figs):
    """
    Renders the Data Stream Visualization tab.

    Parameters
    ----------
    X : array-like
        Feature matrix
    y : array-like
        Target variable
    drift_point : int
        Drift point index
    feature_names : list
        List of feature names
    all_figs : list
        List of matplotlib figures generated by visualize_data_stream
    """
    st.header("1. Data Stream Visualization")
    st.markdown("This section visualizes the generated data before and after the drift point.")

    # Define plot names and their assumed index based on creation
    # order in visualize_data_stream
    PLOT_OPTIONS = {
        "Feature Space Distribution for particular features": 0,  # Assumed first plot
        "Feature vs Index Plots": 1,      # Assumed second plot
        "Target vs Index Plot": 2,        # Assumed third plot
        "Feature Space Distribution": 3,  # Assumed fourth plot
    }
    DEFAULT_PLOT = "Feature Space Distribution for particular features"

    # Plot selection dropdown
    plot_choice = st.selectbox(
        "Select Plot to View",
        options=list(PLOT_OPTIONS.keys()),
        index=list(PLOT_OPTIONS.keys()).index(DEFAULT_PLOT),
        help="Choose one of the visualizations of the data stream. "
             "**Note**: The exact plots available depend on the data generation function."
    )

    # Display the selected plot
    selected_index = PLOT_OPTIONS[plot_choice]

    if selected_index < len(all_figs):
        st.subheader(f"Plot: {plot_choice}")
        st.pyplot(all_figs[selected_index])
    else:
        st.warning(
            f"The selected plot ('{plot_choice}') is not available for the currently selected dataset type. "
            "Showing the first available plot instead."
        )
        if all_figs:
            st.subheader(f"Plot: {list(PLOT_OPTIONS.keys())[0]}")
            st.pyplot(all_figs[0])
        else:
            st.error("No visualization plots were generated.")
